version: 3

project:
  locator: git+github.com/TraderCharts/trader-charts-frontend
  id: git@github.com:TraderCharts/trader-charts-frontend.git
  name: trader-charts-frontend

analyze:
  excludes:
    - "**/node_modules/**"

overrides:
  # License false-positives
  - name: node-forge
    version: "1.3.1"
    license: "GPL-1.0-only"
    verdict: "false-positive"
    reason: "node-forge can be used under the BSD license; the GPL-1.0-only designation is not applicable."

  - name: node-forge
    version: "1.3.1"
    license: "GPL-2.0-only"
    verdict: "false-positive"
    reason: "node-forge can be used under the BSD license; the GPL-2.0-only designation is not applicable."

  - name: jsdom
    version: "16.7.0"
    license: "LGPL-2.0-or-later"
    verdict: "false-positive"
    reason: "jsdom is used in a way that does not trigger LGPL obligations; static linking is not required."

  - name: rc-util
    version: "5.44.4"
    license: "facebook-patent-rights-2"
    verdict: "false-positive"
    reason: "rc-util usage in this project does not trigger Facebook patent restrictions and is considered safe."

  # Security false-positives
  - name: webpack-dev-server
    version: "4.15.2"
    type: "security"
    verdict: "false-positive"
    reason: |
      This vulnerability affects webpack-dev-server versions prior to 5.2.1. In this project, 
      webpack-dev-server is used only for development purposes (live reload and hot module 
      replacement) and is never included in production bundles. This issue does not affect 
      the deployed application.

  - name: webpack-dev-server
    version: "4.15.2"
    type: "security"
    verdict: "false-positive"
    reason: |
      Origin Validation Error in webpack-dev-server <5.2.1 affects development servers 
      by allowing potential WebSocket hijacking in non-Chromium browsers. In this project, 
      the development server is never exposed publicly in production. This issue does not 
      affect the deployed application.
